title: AliFix
description: Free solutions for computer and mobile phone errors
theme: jekyll-theme-cayman
locale: US-EN
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:categories/:year/:month/:day/:title:output_ext
