title: AliFix
description: Bilgisayar ve cep telefonu hataları için ücretsiz çözümler
theme: jekyll-theme-cayman
locale: tr-TR
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:categories/:year/:month/:day/:title:output_ext
